# Generated by Django 5.0 on 2023-12-29 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_photo_alter_photogallery_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photogallery',
            name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='photogallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.photogallery'),
        ),
    ]
