# Generated by Django 5.0 on 2023-12-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_photogallery_photo_photo_photogallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallery',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
